import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className='menuItems'>
          <li><Image src={"/apple.png"} alt="icon" width={40} height={40}/></li>
          <li>
            <Link className='link' href={`/store`}>
              Store
            </Link>
          </li  >
          <li>
            <Link className='link' href={`/Mac`}>
              Mac
            </Link>
          </li>
          <li>
            <Link className='link' href={`/ipad`}>
              iPad
            </Link>
          </li>
          <li>
            <Link className='link' href={`/iphone`}>
              iPhone
            </Link>
          </li>
          <li>
            <Link className='link' href={`/vision`}>
              Vision
            </Link>
          </li>
          <li>
            <Link className='link' href={`/airPods`}>
              AirPods
            </Link>
          </li>
          <li>
            <Link className='link' href={`/tvHome`}>
              TV & Home
            </Link>
          </li>
          <li>
            <Link className='link' href={`/entertainment`}>
              Entertainment
            </Link>
          </li>
          <li>
            <Link className='link' href={`/accessories`}>
              Accessories
            </Link>
          </li>
          <li>
            <Link className='link' href={`/support`}>
              Support
            </Link>
          </li>        
        </ul>      
        <hr />
        {children}
      </body>
    </html>
  )
}
